### ISSUE TITLE
references ga-dc/curriculum

### ISSUE THREAD

**Issue by jshawl** [ga-dc/project1#210]
https://github.com/search?utf8=%E2%9C%93&q=ga-dc%2Fcurriculum+user%3Aga-wdi-exercises&type=Code&ref=searchresults

**Comment by mattscilipoti** [comment]
Fixed in 3cc5ca8f1829d1bc7cd58eca00a489703b71c355

**Comment by jshawl** [comment]
not fixed until https://github.com/ga-wdi-exercises/project1/commit/ead25fbb1abf782bf08435170d36aea87aeb0347 fyi @mattscilipoti
